identifier: "TCA.Languages.Spanish"
name: "Spanish"
version: "1.0.0"
author: "TCAdmin"
shortDescription: "Spanish language"
longDescription: |
  # Spanish translation
  Default **Spanish** translation
  
  ## What's new in 1.0.0
  - Initial release
  
icon: "<svg viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\" stroke=\"currentColor\" stroke-width=\"4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"6\" y=\"6\" width=\"36\" height=\"36\" rx=\"3\"/><path d=\"M13.9 31 L13.9 17 L21.9 17\"/><path d=\"M13.9 24 L21.4 24\"/><path d=\"M13.9 31 L21.4 31\"/><path d=\"M33.74 21.41 C32.84 20.47 31.76 20 30.5 20 C28.52 20 26.9 21.26 26.9 22.75 C26.9 24.24 28.52 25.03 30.5 25.5 C32.48 25.97 34.1 26.76 34.1 28.25 C34.1 29.74 32.48 31 30.5 31 C29.15 31 28.07 30.53 27.26 29.59\"/></svg>"
tags:
  - "Language"
files:
  - path: "Spanish.json"
    type: "LanguageConfig"
