identifier: "TCA.Languages.Hungarian"
name: "Hungarian"
version: "1.0.0"
author: "TCAdmin"
shortDescription: "Hungarian language"
longDescription: |
  # Hungarian translation
  Default **Hungarian** translation
  
  ## What's new in 1.0.0
  - Initial release
  
icon: "<svg viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\" stroke=\"currentColor\" stroke-width=\"4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"6\" y=\"6\" width=\"36\" height=\"36\" rx=\"3\"/><path d=\"M13 17 L13 31\"/><path d=\"M21 17 L21 31\"/><path d=\"M13 24 L21 24\"/><path d=\"M26 20 L26 26.5 A4.5 4.5 0 0 0 35 26.5\"/><path d=\"M35 20 L35 31\"/></svg>"
tags:
  - "Language"
files:
  - path: "Hungarian.json"
    type: "LanguageConfig"
