identifier: "Community.Scripts.BranchSwitcher"
name: "Steam Branch Switcher"
version: "1.0.0"
author: "TCAdmin"
shortDescription: "Steam Branch Switcher"
longDescription: |
  # Steam Branch Switcher
  
  ## Description
  Allows the user to select the branch.
  
  ## Instructions
  - Install the script.
  - Go to Global Game Scripts > Branch Switcher. Select the Steam games that will use it.
  - Go back to the list of scripts > Execute Permissions > Configure the roles that can execute the script.
icon: "<path d=\"M0 0h24v24H0z\" fill=\"none\"/><path d=\"M22 11V3h-7v3H9V3H2v8h7V8h2v10h4v3h7v-8h-7v3h-2V8h2v3z\"/>"
tags:
  - "GameScript"
files:
  - path: "Branch Switcher.json"
    type: "GameScript"
