identifier: "TCA.Languages.Arabic"
name: "Arabic"
version: "1.0.0"
author: "TCAdmin"
shortDescription: "Arabic language"
longDescription: |
  # Arabic translation
  Default **Arabic** translation
  
  ## What's new in 1.0.0
  - Initial release
  
icon: "<svg viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\" stroke=\"currentColor\" stroke-width=\"4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"6\" y=\"6\" width=\"36\" height=\"36\" rx=\"3\"/><path d=\"M12.65 31 L17.65 17 L22.65 31\"/><path d=\"M14.85 26 L20.45 26\"/><path d=\"M27.65 31 L27.65 20\"/><path d=\"M27.65 24.5 A4.5 4.5 0 0 1 35.33 21.32\"/></svg>"
tags:
  - "Language"
files:
  - path: "Arabic.json"
    type: "LanguageConfig"
