identifier: "Community.Games.AmericasArmy3"
name: "America's Army 3"
version: "1.0.0"
author: "TCAdmin"
shortDescription: "AA3"
longDescription: |
  # America's Army 3
  
  ## Description
  America's Army 3 is a first-person shooter video game, the sequel to America's Army.
icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Americasarmy-logo.svg/1280px-Americasarmy-logo.svg.png"
images:
  - "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/13140/header.jpg"
tags:
  - "Game"
  - "Windows"
files:
  - path: "AA3 - Windows.json"
    type: "GameConfig"
